### PR TITLE
Patch win py38

### LINKED ISSUE #41: Add support for Windows (WSL is already supported)
With #36 and cruft 2.0 we officially dropped support for Windows. See #39 for the reasoning behind this change.

Creating this issue to track interest for adding back Windows support and to discuss how to implement the same.

### PR DESCRIPTION
**Pull request by juhuebner**
Fixes #41 

The problem with Windows are:
* In the way cruft works, git marks some files (packs) in the repos as read-only and then `TemporaryDirectory()` can't perform a `cleanup()`. For this one has to move (for now) to python 3.8 (this was fixed around here https://github.com/python/cpython/pull/10320)
* If `gitpython `still has some hand to the repo within the `TemporaryDirectory()` then as well `cleanup()` will crash. To this end, the repo instance has to move into its own context, such that it is closed before `TemporaryDirectory().cleanup()`
* The path handling is different in Windows of course, so the diffing method implemented in https://github.com/cruft/cruft/blob/fc202beb3ff290ef859dd662ab3507631c9eec4c/cruft/_commands/utils/diff.py#L10 has to be altered.

I inter alia got these points somehow working within this PR

### CODE REVIEW

**Comment by juhuebner** [comment]
It works on windows though ;)
I'll see if I get to pass the other workflow actions as well...

**Comment by juhuebner** [comment]
Just a comment on the quick-(nasty)-hack teardowns I added like in [here](https://github.com/juhuebner/cruft/blob/30b752d5799361b318c6ecf1cf85791480e020eb/cruft/_commands/check.py#L40)

Somehow the choking (s.a. https://github.com/copier-org/copier/issues/345)  between the inner and outer context, i.e., between the `repo.close()` and tmpdir`.cleanup()` below only(?) arises in the pytest runs, and this not even deterministically. Although, it did not so on my PC (Windows Server 2019 python Docker image).
Maybe there is some (asynchronous) parallelism going on, since in the git module invokes [git itself via processes](https://github.com/gitpython-developers/GitPython/blob/3dd71d3edbf3930cce953736e026ac3c90dd2e59/git/cmd.py#L144). 
So a better solution should check for the processes or alter `repo.close().`

```python
from tempfile import TemporaryDirectory
from git import Repo

# Set up a nested context.
with TemporaryDirectory() as tmpdir:
    with Repo.clone_from("https://github.com/cruft/cookiecutter-test", tmpdir) as repo:
        last_commit = repo.head.object.hexsha
        print('last_commit:', last_commit)
```
_Usually_, this runs fine...

**Comment by juhuebner** [comment]
addon: the _choking_ probably happens somewhere [here](https://github.com/gitpython-developers/GitPython/blob/3dd71d3edbf3930cce953736e026ac3c90dd2e59/git/repo/base.py#L229)

**Comment by juhuebner** [comment]
Fixes #41 

_inter alia:_
* Introduced refined `tempfile.TemporaryDirectory().cleanup()` in `AltTemporaryDirectory` in `iohelpers.py`
* introduced OS selective path handling in `diff.py`
* added test for Windows case conc. read-only files
  * also a `windows-latest` for py38 in CI  
* altered _test.sh_ for selecting OS dependent conditions

**Comment by samj1912** [comment]
@juhuebner thanks for the PR, sadly I haven't had a chance to go through this in depth yet as this is a big change. I hope to go through it this coming weekend.

**Comment by jonzarecki** [comment]
Seems even more relevant ATM, as more users are using python 3.8 (anaconda's base environment, etc.)

**Comment by jonzarecki** [comment]
I think you can close this PR

**Pull request closed without merging**
