### PR TITLE
Bump portray 1.6→1.7

### LINKED ISSUE #156: Failure in portray command for docs
https://github.com/cruft/cruft/runs/6100661586?check_suite_focus=true

```
Run poetry run portray on_github_pages -f

⠋ Copying source documentation to temporary compilation directory
Done Copying source documentation to temporary compilation directory

⠋ Auto generating reference documentation using pdocs
⠙ Auto generating reference documentation using pdocs
⠹ Auto generating reference documentation using pdocs
Done Auto generating reference documentation using pdocs

⠋ Rendering complete website from Markdown using MkDocs
Traceback (most recent call last):
  File "/home/runner/work/cruft/cruft/.venv/bin/portray", line 8, in <module>
    sys.exit(__hug__.cli())
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/api.py", line 441, in __call__
    result = self.commands.get(command)()
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/interface.py", line 650, in __call__
    raise exception
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/interface.py", line 646, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/api.py", line 184, in on_github_pages
    with render.documentation_in_temp_folder(project_config) as (_, site_dir):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/render.py", line 155, in documentation_in_temp_folder
    mkdocs(config["mkdocs"])
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/render.py", line 69, in mkdocs
    config_instance = _mkdocs_config(config)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/render.py", line 172, in _mkdocs_config
    config_instance = mkdocs_config.Config(schema=mkdocs_config.DEFAULT_SCHEMA)
AttributeError: module 'mkdocs.config' has no attribute 'DEFAULT_SCHEMA'
```

### PR DESCRIPTION
**Pull request by maresb**
Closes #156

### CODE REVIEW

**Comment by maresb** [comment]
@samj1912,  Portray [pins](https://github.com/timothycrosley/portray/blob/75392a1546d04df0835328f445495c07e1858563/pyproject.toml#L12) `mkdocs = "~1.2"` which is forbidden by safety. I don't know how to proceed.

**Comment by samj1912** [comment]
`~1.2` should be compatible with `1.3` right?

**Comment by maresb** [comment]
LOL, look at the example here: https://python-poetry.org/docs/dependency-specification/#tilde-requirements

Here's a reference for the XSS vuln in mkdocs:
https://github.com/mkdocs/mkdocs/commit/5cf196361bb0f8364f667ed98888ffa064982efa

**Comment by maresb** [comment]
Poetry's `~` is not PEP 440's `~=`. [Reference](https://github.com/python-poetry/poetry/issues/380#issuecomment-411250928).

**Comment by samj1912** [comment]
Hmm, I guess the given issue isn't affecting cruft's output wheel since portray and mkdocs are dev dependencies. I think we should be okay using mkdocs 1.2 and adding a safety exclusion at https://github.com/cruft/cruft/blob/211e1eb67f3db185f025ca4e2b22ad9b5b813b17/scripts/lint.sh#L11

Thanks for tackling this :)!

**Review by samj1912 — APPROVED** [review]

**Comment by samj1912** [comment]
Merged and released in 2.10.2 :)

**Pull request merged**
