### PR TITLE
Support projects in sub-directories.

### PR DESCRIPTION
**Pull request by jgontrum**
Fixes https://github.com/cruft/cruft/issues/86

### CODE REVIEW

**Comment by juhuebner** [comment]
I would use consistently `--directory` [here](https://github.com/jgontrum/cruft/blob/a2308498d127020e4de5fa83103f07f4594a23ab/cruft/_cli.py#L208) as well

**Comment by jgontrum** [comment]
> I would use consistently `--directory` [here](https://github.com/jgontrum/cruft/blob/a2308498d127020e4de5fa83103f07f4594a23ab/cruft/_cli.py#L208) as well

Yes, seems like a better name. I've replace it in the code.

**Comment by samj1912** [comment]
@jgontrum Please take a look at #78 which I think solves this in a cleaner manner. I am waiting for my comments there to be addressed. Would you like to collaborate with @jlec on that PR instead?

**Comment by samj1912** [comment]
Fixed by #78

**Pull request closed without merging**
