### PR TITLE
Fix several test issues

### PR DESCRIPTION
**Pull request by HappyEinara**
In neatly separated commits, this PR makes the following updates to testing:

- Update Black to the latest version.
  - Prior version throws an asyncio error in python 3.9
  - On the prior version, switching between python versions with the same `black` cache caused errors relating to the change in default Pickle protocol in 3.8.
- Change references to the default branch `master` on @timothycrosley's test repo to the new default branch `main`.
- Make cruft's own `cruft check` run happily by updating to the latest version of @timothycrosley's package template.
- Update `mypy` to resolve false positive errors that were output on the prior version.
- Update `portray` to resolve a Safety warning on its dependency `mkdocs-material`.
- Add python3.9 to the Github Actions testing matrix.

The full `done.sh` test suite now passes successfully for me using tox on Ubuntu to verify on 3.6, 3.7, 3.8 and 3.9.

Let me know if you feel any of these changes need splitting out into separate PRs. Otherwise when you're done reviewing I can rebase and squash them into a single commit if you prefer.

### CODE REVIEW

**Comment by HappyEinara** [comment]
NB; I'm not sure how the docs are built and deployed, nor does this seem to be covered by cruft's tests. I updated `portray` blindly as it resolved the Safety warning on `mkdocs-material` but before this can be merged, we should check that updating Portray won't break anything.

**Comment by timothycrosley** [comment]
I expect updating portray to be peaceful - if you want to sanity check it you can run `portray in_browser` and spot check the produced documentation.

**Review by timothycrosley — APPROVED** [review]
:tada:

**Comment by HappyEinara** [comment]
Oh wow, that's a pretty nifty tool! Output looks fine to me.

**Review by samj1912 — APPROVED** [review]
Thanks for the PR! :D

**Pull request merged**
