### PR TITLE
Store the checkout value in .cruft.json

### PR DESCRIPTION
**Pull request by languitar**
We are currently rolling out renovate for automatic package upgrade pull requests. One thing we would also like to automate this way is cruft updates. Despite cruft not being officially supported, the [regex manager in renovate](https://docs.renovatebot.com/modules/manager/regex/) could be used for this purpose. However, renovate only works reliably on version numbers whereas cruft currently only places commit shas in `.cruft.json`. That way, an integration of both tools is currently not possible.

With this PR the `checkout` value given via the command line interface is placed in the `.cruft.json` file alongside the existing `commit` value. Renovate can then use this value for looking for updates and subsequently calling `curft update -c <new version>`.

This MR doesn't touch `commit`, because when putting the checkout value directly there, then things like the existing `check` command start falling apart.

For the reference, this kind of renovate configuration could work here:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "enabledManagers": ["regex"],
  "regexManagers": [
    {
      "fileMatch": ["^.cruft.json$"],
      "matchStrings": [
          "\"template\": \"(?<depName>.*?)\",\\n *\"checkout\": \"(?<currentValue>.*?)\""
      ],
      "datasourceTemplate": "git-tags"
    }
  ],
  "postUpgradeTasks": {
      "commands": ["git checkout . && cruft update -y --not-strict -c '{{{toVersion}}}' || echo \"run cruft update manually!\" > CRUFT_UPDATE_FAILED"],
      "fileFilters": ["**/*"]
  }
}

```

### CODE REVIEW

**Comment by languitar** [comment]
@timothycrosley @samj1912 any chance to get some feedback on this? Is there any chance for this to get merged or do I need another way to resolve the problem?

**Review by samj1912 — APPROVED** [review]

**Comment by samj1912** [comment]
Seems like a harmless change. Happy to merge it in. I guess in the longer term, it can also be used to prepopulate the checkout value if it is not provided?

**Comment by languitar** [comment]
> Seems like a harmless change. Happy to merge it in.

Thanks for merging this! Is there a chance to generate a release with this change?

> I guess in the longer term, it can also be used to prepopulate the checkout value if it is not provided?

In the case of using renovate for automated updates we don't want to pre-populate the checkout value, because we would use tags then. Renovate mostly works on semantic versions and not on commit hashes which cannot be compared. Therefore, on the next `curft update` a new checkout value will be provided with the updated tag name anyways.

**Comment by samj1912** [comment]
Yup, will prepare a release later tonight :)

**Comment by samj1912** [comment]
This should be merged now :)

**Pull request merged**
