### PR TITLE
implement support for local extensions

### LINKED ISSUE #172: Local extensions don't work with (Cookiecutter 2.1.1)
The standard examples for local extensions in the Cookiecutter docs don't work with cruft. Creating a `local_extensions` folder with an `__init__.py`, or a `local_extensions.py` file in the root of the template should make `local_extensions` importable as a module, but it fails with Cruft because the working directory is not set to the path of `cookiecutter.json` (or alternatively, the Python search path is updated to include that directory).

### PR DESCRIPTION
**Pull request by Chilipp**
Thanks for this awesome package!

This PR aims to close #172 and implement support for local extensions. It mimics the original implementation in cookiecutter (cookiecutter/cookiecutter#1240) that unfortunately seems not to be part of the python API

I also implemented two tests (d1355db00f15473e0130d6e09910d824a909b3b7), one for the creation and one for the update. But currently I am using a fork of the [`cookiecutter-test`](https://github.com/cruft/cookiecutter-test) repo. You need to copy the [local-extension](https://github.com/Chilipp/cookiecutter-test/tree/local-extension) and [local-extension-update](https://github.com/Chilipp/cookiecutter-test/tree/local-extension-update) from my fork to the original repository (or [create the two branches in the original repository](https://github.com/cruft/cookiecutter-test/branches) and I make a PR).

one question remains though: Do we really want to use

```python
from cookiecutter.main import _patch_import_path_for_repo
``` 

or should we rather copy that small code snippet from cookiecutter (see https://github.com/cookiecutter/cookiecutter/blob/cf81d63bf3d82e1739db73bcbed6f1012890e33e/cookiecutter/main.py#L139)

### ToDos:

- [x] create test branches in [cookiecutter-test](https://github.com/cruft/cookiecutter-test/branches) repo
- [x] clarify strategy for `_patch_import_path_for_repo`

### CODE REVIEW

**Comment by Chilipp** [comment]
@timothycrosley is there any chance to get this merged or anything else that I can do to speed this up?

**Comment by MichalKubek** [comment]
@Chilipp I thing will be better to copy that functionality to this repository, because it is private function.
also we can fix this problem with this implementation https://github.com/MichalKubek/cruft/commit/5e3ca7585f9f7c6577e7f6522f32948e8745f74d

**Comment by Chilipp** [comment]
True! Sounds good, thanks @MichalKubek do you want to implement your approach in this PR or shall I do it (will take about an hour until I can do it)

**Comment by MichalKubek** [comment]
@Chilipp please you do it. It is your PR.

Thanks

**Comment by Chilipp** [comment]
hey @MichalKubek! sorry, was busy with a lot of other stuff. But I fixed it now. Although your solution is nicer, I had to add support for a `directory` parameter in the `AltTemporaryDirectory`. And as this class is used in many places, I had to touch quite some files (see https://github.com/cruft/cruft/compare/a18aa92..7c63ae4)

**Comment by Chilipp** [comment]
Hmm, when I compare the implementation with `AltTemporaryDirectory`

https://github.com/cruft/cruft/compare/808842d..0c681ef

to the original implementation I suggested,

https://github.com/cruft/cruft/compare/35a2fbf..0c681ef

then my original implementation involved much less code modification and looks less hacky to me. what do you think @MichalKubek ?

**Comment by samj1912** [comment]
@Chilipp could you please create a PR to https://github.com/cruft/cookiecutter-test with your changes?

**Comment by Chilipp** [comment]
alright @samj1912 , but I need two branches. one for the creation (https://github.com/Chilipp/cookiecutter-test/tree/local-extension) and one for the update (https://github.com/Chilipp/cookiecutter-test/tree/local-extension-update)

**Comment by samj1912** [comment]
Created https://github.com/cruft/cookiecutter-test/tree/extensions-update

**Comment by Chilipp** [comment]
alright, I updated the tests. so if you are ok with the `AltTemporaryDirectory` implementation (that I do not like so much, see https://github.com/cruft/cruft/pull/237#issuecomment-1490145625), feel free to merge this PR :smiley:

**Review by samj1912 — APPROVED** [review]

**Comment by samj1912** [comment]
Thanks for this PR!

**Comment by Chilipp** [comment]
You're welcome! Thanks for working on `cruft` :smiley:

**Comment by tmeckel** [comment]
@Chilipp still does not work. @samj1912 

```python
Traceback (most recent call last):

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/environment.py", line 35, in __init__
    super().__init__(extensions=extensions, **kwargs)

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/jinja2/environment.py", line 363, in __init__
    self.extensions = load_extensions(self, extensions)

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)

ModuleNotFoundError: No module named 'local_extensions'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/tmp/venv-cookiecutter/bin/cruft", line 8, in <module>
    sys.exit(app())

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cruft/_cli.py", line 282, in diff
    if not _commands.diff(project_dir=project_dir, exit_code=exit_code, checkout=checkout):

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cruft/_commands/diff.py", line 38, in diff
    utils.generate.cookiecutter_template(

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cruft/_commands/utils/generate.py", line 44, in cookiecutter_template
    context = _generate_output(cruft_state, Path(repo.working_dir), cookiecutter_input, output_dir)

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cruft/_commands/utils/generate.py", line 75, in _generate_output
    new_context = generate_cookiecutter_context(

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cruft/_commands/utils/cookiecutter.py", line 98, in generate_cookiecutter_context
    context["cookiecutter"] = prompt_for_config(context, no_input)

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/prompt.py", line 185, in prompt_for_config
    env = StrictEnvironment(context=context)

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/environment.py", line 65, in __init__
    super().__init__(undefined=StrictUndefined, **kwargs)

  File "/tmp/venv-cookiecutter/lib/python3.10/site-packages/cookiecutter/environment.py", line 37, in __init__
    raise UnknownExtension(f'Unable to load extension: {err}')

cookiecutter.exceptions.UnknownExtension: Unable to load extension: No module named 'local_extensions'
```

image

`.cruft.json`:

```json
{
  "template": "/home/vagrant/work/pulumi-tf-provider-cookiecutter",
  "commit": "6ca0d9b24dd7fbff7ec9380c3759a5311ac766e9",
  "checkout": null,
  "context": {
    "cookiecutter": {
      [...]
      "_copy_without_render": [
        ".github/workflows/release.yml"
      ],
      "_extensions": [
        "local_extensions.FilterExtension"
      ],
      "_template": "/home/vagrant/work/pulumi-tf-provider-cookiecutter"
    }
  },
  "directory": null
}
```

**Comment by Chilipp** [comment]
Weird! @tmeckel Can you please try 

```bash
cruft create https://github.com/cruft/cookiecutter-test --checkout extensions --directory dir
```

Does that work? How is your setup different from [that branch](https://github.com/cruft/cookiecutter-test/tree/extensions)?

**Comment by tmeckel** [comment]
@Chilipp my template (https://github.com/tmeckel/pulumi-tf-provider-cookiecutter) uses a local extension module [local_extensions.py](https://github.com/tmeckel/pulumi-tf-provider-cookiecutter/blob/master/local_extensions.py) in the top-level directory. 

For testing I changed the cruft module locally and added the following code:

```grep
_commands/utils/generate.py:90:        sys.path.append(tmpdir)
_commands/diff.py:36:            sys.path.append(cruft_state["template"])
_commands/create.py:46:        sys.path.append(cookiecutter_template_dir)
```

After that cruft was able to create/update and diff.

As far as I understood the code 

```grep
_commands/utils/iohelper.py:16:            sys.path.append(name)
```

should've done the trick. But I didn't.

**Comment by Chilipp** [comment]
hey @tmeckel! just tested it with

```bash
git clone https://github.com/tmeckel/pulumi-tf-provider-cookiecutter
git -C pulumi-tf-provider-cookiecutter rm -r hooks
git -C pulumi-tf-provider-cookiecutter commit -m "remove hooks"
cruft create pulumi-tf-provider-cookiecutter --no-input
```

and everything went well. Does the command I wrote in my previous comment https://github.com/cruft/cruft/pull/237#issuecomment-1499481771 work for you? If not, and sorry for the stupid question, are you sure you are using the correct version? What do you get when you run

```bash
python -c "import cruft; print(cruft.__version__)"
```
I am getting `2.14.0`

Alternatively I'd say that you should open a new issue (but I am not a maintainer of cruft and so I am not moderating this PR :wink: )

**Pull request merged**
