### PR TITLE
Don't ignore globs when skipping files for update

### LINKED ISSUE #295: BUG: Globs are ignored in skip list
According to the docs, you can provided a `skip` list of files that should be ignored during updates. The docs also state that this list can contain `globs`, however, these globs are ignored in the latest version.

### PR DESCRIPTION
**Pull request by RobertDeRose**
The logic in `_remove_paths` checks if the path is a `str` or `Path` object and only if it is a `str` does it assume it contains a glob. Unfortunately, the `_get_skip_paths` method was wrapping all returned values in `Path` objects so globs were being ignored.

Fixes #295 
Closes #258

### CODE REVIEW

**Comment by RobertDeRose** [comment]
@millsks You made the last commit 9 months ago. Is this project dead? This is the second PR to address this issue, I didn't see #258 which has been open since June 2023. I think my PR addresses the issue a little more closely to the current code style, with proper type hints, but one of these needs to be merged as it's a broken feature.

**Comment by millsks** [comment]
Hi Robert.  I do not believe this project is dead.  I just got side tracked by a move recently and trying to get everything situated again.  I would say your PR would supercede mine if it takes unto account the latest code style.

**Comment by RobertDeRose** [comment]
> Hi Robert. I do not believe this project is dead. I just got side tracked by a move recently and trying to get everything situated again. I would say your PR would supercede mine if it takes unto account the latest code style.

Completely understood.  Would appreciate a merge if this meets the maintainers satisfaction. 
Glad to hear the project is not dead. Other than this issue, it's currently working pretty well for us. I would like to contribute some new features as time permits.

**Comment by millsks** [comment]
Hi Robert.  Sorry I misunderstood the previous comment.  I am not a maintainer, but instead a contributor just like yourself.

@samj1912 are you available to review this PR?

**Review by sambhav — APPROVED** [review]

**Pull request merged**
