### PR TITLE
Improve update command

### PR DESCRIPTION
**Pull request by gmsantos**
This PR tries to improve how the update command works in cases where the cookiecutter template receives new variable values.

It handles two scenarios:

- When you want to update an input value by using the `--cookiecutter-input` flag
- When you want your project to be updated based on updates in [private variables](https://cookiecutter.readthedocs.io/en/latest/advanced/private_variables.html) from the cookiecutter template with a new `--refresh-private-variables` flag (feel free to suggest some better naming 😄 )

To test those changes, I created a fork of the https://github.com/cruft/cookiecutter-test repo and used those two branches:

https://github.com/gmsantos/cookiecutter-test/tree/input
https://github.com/gmsantos/cookiecutter-test/tree/input-updated

Those branches can be added back in a similar way as https://github.com/cruft/cookiecutter-test/pull/1 (I can sync the tests after that).

### CODE REVIEW

**Comment by gmsantos** [comment]
@samj1912 let me know when you have some time to review this one :)

**Comment by simu** [comment]
I was planning to submit a similar PR (see my proposal in https://github.com/cruft/cruft/issues/57#issuecomment-1131821551), good to see we're not the only ones looking for a more versatile update command.

**Comment by lsorber** [comment]
With Cookiecutter 2.2.0's support for [boolean variables](https://cookiecutter.readthedocs.io/en/latest/advanced/boolean_variables.html), perhaps this PR could also be extended to support transitioning from string values such as "0" or "1" to the boolean values `true` and `false` automatically (when the Cookiecutter template uses boolean values)?

Specifically, the documentation on boolean variables says that these values should map to `True` and `False`, respectively:
1. `True` values: “1”, “true”, “t”, “yes”, “y”, “on”
2. `False` values: “0”, “false”, “f”, “no”, “n”, “off”

**Comment by gmsantos** [comment]
@lsorber not sure if is related to these changes. Better do it in a separate PR.

**Comment by stefan-caraiman** [comment]
bump, any updates on this feature?

**Pull request merged**
