### PR TITLE
Bump importlib metadata version

### LINKED ISSUE #152: Upgrade version of importlib-metadata
Currently, cruft pins the major version of importlib-metadata to 3. This is really out of date.

[importlib-metadata](https://pypi.org/project/importlib-metadata/) is currently at v4.11.3

The latest version of sphinx requires at least v4.4 of importlib-metadata and so currently, there is an incompatibility that is forcing me to use an old version of sphinx.

Please simply change [this line](https://github.com/cruft/cruft/blob/0c6de85d974197969c0e65913857eaa36b788e5e/pyproject.toml#L17) to me some more recent version (e.g. `">=3.4"`)

@samj1912 are you happy with this?

### PR DESCRIPTION
**Pull request by samj1912**
Fixes #152

### CODE REVIEW

**Comment by adamcunnington-mlg** [comment]
@samj1912 just checking you saw this failure and are able to address? thanks

**Comment by rxm7706** [comment]
@samj1912 @adamcunnington-mlg 
Looking at 
https://github.com/python-poetry/poetry-core/blob/d487e8b1c12bc6a91b5aee04d5ae445204e06635/pyproject.toml#L39
https://github.com/python-poetry/poetry/blob/dca0c562c42cb79a494eff982fc8a52c632100f4/pyproject.toml#L34

Looks like should be using importlib-metadata and adding the 
importlib-metadata = {version = ">=1.7.0", python = "<3.8"}

Poetry Requirements and Cruft Poetry Requirements look quite different.

**Comment by adamcunnington-mlg** [comment]
@samj1912 sure, I'd agree with that - can you make the fix?

Thanks

**Comment by samj1912** [comment]
Fixed in #154

**Pull request closed without merging**
